name: Build

on:
  push:
    branches: [ master ]
    paths:
      - 'MultiplayerExtensions/**'
      - '.github/workflows/Build.yml'
      - 'Refs/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'MultiplayerExtensions/**'

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: GetStrippedRefs
      env:
        FILES_URL: ${{ secrets.BSFILES_URL }}
      run: wget --no-check-certificate "$FILES_URL" -q -O bsfiles.zip
    - name: ExtractRefs
      run: unzip -q -n bsfiles.zip -d ./Refs
    - name: Test
      id: Test
      run: dotnet test --logger GitHubActions
